package it.etoken.base.model.eosblock.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ActivityStageExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public ActivityStageExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andActivityIdIsNull() {
			addCriterion("activity_id is null");
			return (Criteria) this;
		}

		public Criteria andActivityIdIsNotNull() {
			addCriterion("activity_id is not null");
			return (Criteria) this;
		}

		public Criteria andActivityIdEqualTo(Long value) {
			addCriterion("activity_id =", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotEqualTo(Long value) {
			addCriterion("activity_id <>", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdGreaterThan(Long value) {
			addCriterion("activity_id >", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("activity_id >=", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdLessThan(Long value) {
			addCriterion("activity_id <", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdLessThanOrEqualTo(Long value) {
			addCriterion("activity_id <=", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdIn(List<Long> values) {
			addCriterion("activity_id in", values, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotIn(List<Long> values) {
			addCriterion("activity_id not in", values, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdBetween(Long value1, Long value2) {
			addCriterion("activity_id between", value1, value2, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotBetween(Long value1, Long value2) {
			addCriterion("activity_id not between", value1, value2, "activityId");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNull() {
			addCriterion("start_date is null");
			return (Criteria) this;
		}

		public Criteria andStartDateIsNotNull() {
			addCriterion("start_date is not null");
			return (Criteria) this;
		}

		public Criteria andStartDateEqualTo(Date value) {
			addCriterion("start_date =", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotEqualTo(Date value) {
			addCriterion("start_date <>", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThan(Date value) {
			addCriterion("start_date >", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateGreaterThanOrEqualTo(Date value) {
			addCriterion("start_date >=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThan(Date value) {
			addCriterion("start_date <", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateLessThanOrEqualTo(Date value) {
			addCriterion("start_date <=", value, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateIn(List<Date> values) {
			addCriterion("start_date in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotIn(List<Date> values) {
			addCriterion("start_date not in", values, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateBetween(Date value1, Date value2) {
			addCriterion("start_date between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andStartDateNotBetween(Date value1, Date value2) {
			addCriterion("start_date not between", value1, value2, "startDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNull() {
			addCriterion("end_date is null");
			return (Criteria) this;
		}

		public Criteria andEndDateIsNotNull() {
			addCriterion("end_date is not null");
			return (Criteria) this;
		}

		public Criteria andEndDateEqualTo(Date value) {
			addCriterion("end_date =", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotEqualTo(Date value) {
			addCriterion("end_date <>", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThan(Date value) {
			addCriterion("end_date >", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateGreaterThanOrEqualTo(Date value) {
			addCriterion("end_date >=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThan(Date value) {
			addCriterion("end_date <", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateLessThanOrEqualTo(Date value) {
			addCriterion("end_date <=", value, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateIn(List<Date> values) {
			addCriterion("end_date in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotIn(List<Date> values) {
			addCriterion("end_date not in", values, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateBetween(Date value1, Date value2) {
			addCriterion("end_date between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andEndDateNotBetween(Date value1, Date value2) {
			addCriterion("end_date not between", value1, value2, "endDate");
			return (Criteria) this;
		}

		public Criteria andCommonCountIsNull() {
			addCriterion("common_count is null");
			return (Criteria) this;
		}

		public Criteria andCommonCountIsNotNull() {
			addCriterion("common_count is not null");
			return (Criteria) this;
		}

		public Criteria andCommonCountEqualTo(Long value) {
			addCriterion("common_count =", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountNotEqualTo(Long value) {
			addCriterion("common_count <>", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountGreaterThan(Long value) {
			addCriterion("common_count >", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountGreaterThanOrEqualTo(Long value) {
			addCriterion("common_count >=", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountLessThan(Long value) {
			addCriterion("common_count <", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountLessThanOrEqualTo(Long value) {
			addCriterion("common_count <=", value, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountIn(List<Long> values) {
			addCriterion("common_count in", values, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountNotIn(List<Long> values) {
			addCriterion("common_count not in", values, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountBetween(Long value1, Long value2) {
			addCriterion("common_count between", value1, value2, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonCountNotBetween(Long value1, Long value2) {
			addCriterion("common_count not between", value1, value2, "commonCount");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyIsNull() {
			addCriterion("common_min_qty is null");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyIsNotNull() {
			addCriterion("common_min_qty is not null");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyEqualTo(Long value) {
			addCriterion("common_min_qty =", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyNotEqualTo(Long value) {
			addCriterion("common_min_qty <>", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyGreaterThan(Long value) {
			addCriterion("common_min_qty >", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyGreaterThanOrEqualTo(Long value) {
			addCriterion("common_min_qty >=", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyLessThan(Long value) {
			addCriterion("common_min_qty <", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyLessThanOrEqualTo(Long value) {
			addCriterion("common_min_qty <=", value, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyIn(List<Long> values) {
			addCriterion("common_min_qty in", values, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyNotIn(List<Long> values) {
			addCriterion("common_min_qty not in", values, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyBetween(Long value1, Long value2) {
			addCriterion("common_min_qty between", value1, value2, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMinQtyNotBetween(Long value1, Long value2) {
			addCriterion("common_min_qty not between", value1, value2, "commonMinQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyIsNull() {
			addCriterion("common_max_qty is null");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyIsNotNull() {
			addCriterion("common_max_qty is not null");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyEqualTo(Long value) {
			addCriterion("common_max_qty =", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyNotEqualTo(Long value) {
			addCriterion("common_max_qty <>", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyGreaterThan(Long value) {
			addCriterion("common_max_qty >", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyGreaterThanOrEqualTo(Long value) {
			addCriterion("common_max_qty >=", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyLessThan(Long value) {
			addCriterion("common_max_qty <", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyLessThanOrEqualTo(Long value) {
			addCriterion("common_max_qty <=", value, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyIn(List<Long> values) {
			addCriterion("common_max_qty in", values, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyNotIn(List<Long> values) {
			addCriterion("common_max_qty not in", values, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyBetween(Long value1, Long value2) {
			addCriterion("common_max_qty between", value1, value2, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andCommonMaxQtyNotBetween(Long value1, Long value2) {
			addCriterion("common_max_qty not between", value1, value2, "commonMaxQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCountIsNull() {
			addCriterion("lucky_count is null");
			return (Criteria) this;
		}

		public Criteria andLuckyCountIsNotNull() {
			addCriterion("lucky_count is not null");
			return (Criteria) this;
		}

		public Criteria andLuckyCountEqualTo(Long value) {
			addCriterion("lucky_count =", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountNotEqualTo(Long value) {
			addCriterion("lucky_count <>", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountGreaterThan(Long value) {
			addCriterion("lucky_count >", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountGreaterThanOrEqualTo(Long value) {
			addCriterion("lucky_count >=", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountLessThan(Long value) {
			addCriterion("lucky_count <", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountLessThanOrEqualTo(Long value) {
			addCriterion("lucky_count <=", value, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountIn(List<Long> values) {
			addCriterion("lucky_count in", values, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountNotIn(List<Long> values) {
			addCriterion("lucky_count not in", values, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountBetween(Long value1, Long value2) {
			addCriterion("lucky_count between", value1, value2, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCountNotBetween(Long value1, Long value2) {
			addCriterion("lucky_count not between", value1, value2, "luckyCount");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyIsNull() {
			addCriterion("lucky_coin_qty is null");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyIsNotNull() {
			addCriterion("lucky_coin_qty is not null");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyEqualTo(Long value) {
			addCriterion("lucky_coin_qty =", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyNotEqualTo(Long value) {
			addCriterion("lucky_coin_qty <>", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyGreaterThan(Long value) {
			addCriterion("lucky_coin_qty >", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyGreaterThanOrEqualTo(Long value) {
			addCriterion("lucky_coin_qty >=", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyLessThan(Long value) {
			addCriterion("lucky_coin_qty <", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyLessThanOrEqualTo(Long value) {
			addCriterion("lucky_coin_qty <=", value, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyIn(List<Long> values) {
			addCriterion("lucky_coin_qty in", values, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyNotIn(List<Long> values) {
			addCriterion("lucky_coin_qty not in", values, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyBetween(Long value1, Long value2) {
			addCriterion("lucky_coin_qty between", value1, value2, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyCoinQtyNotBetween(Long value1, Long value2) {
			addCriterion("lucky_coin_qty not between", value1, value2, "luckyCoinQty");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodIsNull() {
			addCriterion("lucky_method is null");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodIsNotNull() {
			addCriterion("lucky_method is not null");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodEqualTo(String value) {
			addCriterion("lucky_method =", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodNotEqualTo(String value) {
			addCriterion("lucky_method <>", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodGreaterThan(String value) {
			addCriterion("lucky_method >", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodGreaterThanOrEqualTo(String value) {
			addCriterion("lucky_method >=", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodLessThan(String value) {
			addCriterion("lucky_method <", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodLessThanOrEqualTo(String value) {
			addCriterion("lucky_method <=", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodLike(String value) {
			addCriterion("lucky_method like", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodNotLike(String value) {
			addCriterion("lucky_method not like", value, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodIn(List<String> values) {
			addCriterion("lucky_method in", values, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodNotIn(List<String> values) {
			addCriterion("lucky_method not in", values, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodBetween(String value1, String value2) {
			addCriterion("lucky_method between", value1, value2, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andLuckyMethodNotBetween(String value1, String value2) {
			addCriterion("lucky_method not between", value1, value2, "luckyMethod");
			return (Criteria) this;
		}

		public Criteria andTokenNameIsNull() {
			addCriterion("token_name is null");
			return (Criteria) this;
		}

		public Criteria andTokenNameIsNotNull() {
			addCriterion("token_name is not null");
			return (Criteria) this;
		}

		public Criteria andTokenNameEqualTo(String value) {
			addCriterion("token_name =", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotEqualTo(String value) {
			addCriterion("token_name <>", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameGreaterThan(String value) {
			addCriterion("token_name >", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameGreaterThanOrEqualTo(String value) {
			addCriterion("token_name >=", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLessThan(String value) {
			addCriterion("token_name <", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLessThanOrEqualTo(String value) {
			addCriterion("token_name <=", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameLike(String value) {
			addCriterion("token_name like", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotLike(String value) {
			addCriterion("token_name not like", value, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameIn(List<String> values) {
			addCriterion("token_name in", values, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotIn(List<String> values) {
			addCriterion("token_name not in", values, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameBetween(String value1, String value2) {
			addCriterion("token_name between", value1, value2, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenNameNotBetween(String value1, String value2) {
			addCriterion("token_name not between", value1, value2, "tokenName");
			return (Criteria) this;
		}

		public Criteria andTokenContractIsNull() {
			addCriterion("token_contract is null");
			return (Criteria) this;
		}

		public Criteria andTokenContractIsNotNull() {
			addCriterion("token_contract is not null");
			return (Criteria) this;
		}

		public Criteria andTokenContractEqualTo(String value) {
			addCriterion("token_contract =", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractNotEqualTo(String value) {
			addCriterion("token_contract <>", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractGreaterThan(String value) {
			addCriterion("token_contract >", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractGreaterThanOrEqualTo(String value) {
			addCriterion("token_contract >=", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractLessThan(String value) {
			addCriterion("token_contract <", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractLessThanOrEqualTo(String value) {
			addCriterion("token_contract <=", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractLike(String value) {
			addCriterion("token_contract like", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractNotLike(String value) {
			addCriterion("token_contract not like", value, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractIn(List<String> values) {
			addCriterion("token_contract in", values, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractNotIn(List<String> values) {
			addCriterion("token_contract not in", values, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractBetween(String value1, String value2) {
			addCriterion("token_contract between", value1, value2, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andTokenContractNotBetween(String value1, String value2) {
			addCriterion("token_contract not between", value1, value2, "tokenContract");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNull() {
			addCriterion("precision_number is null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNotNull() {
			addCriterion("precision_number is not null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberEqualTo(Integer value) {
			addCriterion("precision_number =", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotEqualTo(Integer value) {
			addCriterion("precision_number <>", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThan(Integer value) {
			addCriterion("precision_number >", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("precision_number >=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThan(Integer value) {
			addCriterion("precision_number <", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThanOrEqualTo(Integer value) {
			addCriterion("precision_number <=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIn(List<Integer> values) {
			addCriterion("precision_number in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotIn(List<Integer> values) {
			addCriterion("precision_number not in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberBetween(Integer value1, Integer value2) {
			addCriterion("precision_number between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("precision_number not between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andSeqIsNull() {
			addCriterion("seq is null");
			return (Criteria) this;
		}

		public Criteria andSeqIsNotNull() {
			addCriterion("seq is not null");
			return (Criteria) this;
		}

		public Criteria andSeqEqualTo(Integer value) {
			addCriterion("seq =", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotEqualTo(Integer value) {
			addCriterion("seq <>", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThan(Integer value) {
			addCriterion("seq >", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqGreaterThanOrEqualTo(Integer value) {
			addCriterion("seq >=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThan(Integer value) {
			addCriterion("seq <", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqLessThanOrEqualTo(Integer value) {
			addCriterion("seq <=", value, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqIn(List<Integer> values) {
			addCriterion("seq in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotIn(List<Integer> values) {
			addCriterion("seq not in", values, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqBetween(Integer value1, Integer value2) {
			addCriterion("seq between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andSeqNotBetween(Integer value1, Integer value2) {
			addCriterion("seq not between", value1, value2, "seq");
			return (Criteria) this;
		}

		public Criteria andIsPaidIsNull() {
			addCriterion("is_paid is null");
			return (Criteria) this;
		}

		public Criteria andIsPaidIsNotNull() {
			addCriterion("is_paid is not null");
			return (Criteria) this;
		}

		public Criteria andIsPaidEqualTo(String value) {
			addCriterion("is_paid =", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidNotEqualTo(String value) {
			addCriterion("is_paid <>", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidGreaterThan(String value) {
			addCriterion("is_paid >", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidGreaterThanOrEqualTo(String value) {
			addCriterion("is_paid >=", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidLessThan(String value) {
			addCriterion("is_paid <", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidLessThanOrEqualTo(String value) {
			addCriterion("is_paid <=", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidLike(String value) {
			addCriterion("is_paid like", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidNotLike(String value) {
			addCriterion("is_paid not like", value, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidIn(List<String> values) {
			addCriterion("is_paid in", values, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidNotIn(List<String> values) {
			addCriterion("is_paid not in", values, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidBetween(String value1, String value2) {
			addCriterion("is_paid between", value1, value2, "isPaid");
			return (Criteria) this;
		}

		public Criteria andIsPaidNotBetween(String value1, String value2) {
			addCriterion("is_paid not between", value1, value2, "isPaid");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosIsNull() {
			addCriterion("need_buy_eos is null");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosIsNotNull() {
			addCriterion("need_buy_eos is not null");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosEqualTo(Long value) {
			addCriterion("need_buy_eos =", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosNotEqualTo(Long value) {
			addCriterion("need_buy_eos <>", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosGreaterThan(Long value) {
			addCriterion("need_buy_eos >", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosGreaterThanOrEqualTo(Long value) {
			addCriterion("need_buy_eos >=", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosLessThan(Long value) {
			addCriterion("need_buy_eos <", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosLessThanOrEqualTo(Long value) {
			addCriterion("need_buy_eos <=", value, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosIn(List<Long> values) {
			addCriterion("need_buy_eos in", values, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosNotIn(List<Long> values) {
			addCriterion("need_buy_eos not in", values, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosBetween(Long value1, Long value2) {
			addCriterion("need_buy_eos between", value1, value2, "needBuyEos");
			return (Criteria) this;
		}

		public Criteria andNeedBuyEosNotBetween(Long value1, Long value2) {
			addCriterion("need_buy_eos not between", value1, value2, "needBuyEos");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table activity_stage
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_stage
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 19 14:04:30 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}