package it.etoken.base.model.eosblock.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.math.BigDecimal;

public class ActivityStageUserExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public ActivityStageUserExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andActivityIdIsNull() {
			addCriterion("activity_id is null");
			return (Criteria) this;
		}

		public Criteria andActivityIdIsNotNull() {
			addCriterion("activity_id is not null");
			return (Criteria) this;
		}

		public Criteria andActivityIdEqualTo(Long value) {
			addCriterion("activity_id =", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotEqualTo(Long value) {
			addCriterion("activity_id <>", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdGreaterThan(Long value) {
			addCriterion("activity_id >", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdGreaterThanOrEqualTo(Long value) {
			addCriterion("activity_id >=", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdLessThan(Long value) {
			addCriterion("activity_id <", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdLessThanOrEqualTo(Long value) {
			addCriterion("activity_id <=", value, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdIn(List<Long> values) {
			addCriterion("activity_id in", values, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotIn(List<Long> values) {
			addCriterion("activity_id not in", values, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdBetween(Long value1, Long value2) {
			addCriterion("activity_id between", value1, value2, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityIdNotBetween(Long value1, Long value2) {
			addCriterion("activity_id not between", value1, value2, "activityId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdIsNull() {
			addCriterion("activity_stage_id is null");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdIsNotNull() {
			addCriterion("activity_stage_id is not null");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdEqualTo(Long value) {
			addCriterion("activity_stage_id =", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdNotEqualTo(Long value) {
			addCriterion("activity_stage_id <>", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdGreaterThan(Long value) {
			addCriterion("activity_stage_id >", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdGreaterThanOrEqualTo(Long value) {
			addCriterion("activity_stage_id >=", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdLessThan(Long value) {
			addCriterion("activity_stage_id <", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdLessThanOrEqualTo(Long value) {
			addCriterion("activity_stage_id <=", value, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdIn(List<Long> values) {
			addCriterion("activity_stage_id in", values, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdNotIn(List<Long> values) {
			addCriterion("activity_stage_id not in", values, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdBetween(Long value1, Long value2) {
			addCriterion("activity_stage_id between", value1, value2, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andActivityStageIdNotBetween(Long value1, Long value2) {
			addCriterion("activity_stage_id not between", value1, value2, "activityStageId");
			return (Criteria) this;
		}

		public Criteria andStatusIsNull() {
			addCriterion("status is null");
			return (Criteria) this;
		}

		public Criteria andStatusIsNotNull() {
			addCriterion("status is not null");
			return (Criteria) this;
		}

		public Criteria andStatusEqualTo(String value) {
			addCriterion("status =", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotEqualTo(String value) {
			addCriterion("status <>", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThan(String value) {
			addCriterion("status >", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusGreaterThanOrEqualTo(String value) {
			addCriterion("status >=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThan(String value) {
			addCriterion("status <", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLessThanOrEqualTo(String value) {
			addCriterion("status <=", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusLike(String value) {
			addCriterion("status like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotLike(String value) {
			addCriterion("status not like", value, "status");
			return (Criteria) this;
		}

		public Criteria andStatusIn(List<String> values) {
			addCriterion("status in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotIn(List<String> values) {
			addCriterion("status not in", values, "status");
			return (Criteria) this;
		}

		public Criteria andStatusBetween(String value1, String value2) {
			addCriterion("status between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andStatusNotBetween(String value1, String value2) {
			addCriterion("status not between", value1, value2, "status");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNull() {
			addCriterion("account_name is null");
			return (Criteria) this;
		}

		public Criteria andAccountNameIsNotNull() {
			addCriterion("account_name is not null");
			return (Criteria) this;
		}

		public Criteria andAccountNameEqualTo(String value) {
			addCriterion("account_name =", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotEqualTo(String value) {
			addCriterion("account_name <>", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThan(String value) {
			addCriterion("account_name >", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameGreaterThanOrEqualTo(String value) {
			addCriterion("account_name >=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThan(String value) {
			addCriterion("account_name <", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLessThanOrEqualTo(String value) {
			addCriterion("account_name <=", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameLike(String value) {
			addCriterion("account_name like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotLike(String value) {
			addCriterion("account_name not like", value, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameIn(List<String> values) {
			addCriterion("account_name in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotIn(List<String> values) {
			addCriterion("account_name not in", values, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameBetween(String value1, String value2) {
			addCriterion("account_name between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andAccountNameNotBetween(String value1, String value2) {
			addCriterion("account_name not between", value1, value2, "accountName");
			return (Criteria) this;
		}

		public Criteria andIsWinnerIsNull() {
			addCriterion("is_winner is null");
			return (Criteria) this;
		}

		public Criteria andIsWinnerIsNotNull() {
			addCriterion("is_winner is not null");
			return (Criteria) this;
		}

		public Criteria andIsWinnerEqualTo(String value) {
			addCriterion("is_winner =", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerNotEqualTo(String value) {
			addCriterion("is_winner <>", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerGreaterThan(String value) {
			addCriterion("is_winner >", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerGreaterThanOrEqualTo(String value) {
			addCriterion("is_winner >=", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerLessThan(String value) {
			addCriterion("is_winner <", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerLessThanOrEqualTo(String value) {
			addCriterion("is_winner <=", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerLike(String value) {
			addCriterion("is_winner like", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerNotLike(String value) {
			addCriterion("is_winner not like", value, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerIn(List<String> values) {
			addCriterion("is_winner in", values, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerNotIn(List<String> values) {
			addCriterion("is_winner not in", values, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerBetween(String value1, String value2) {
			addCriterion("is_winner between", value1, value2, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsWinnerNotBetween(String value1, String value2) {
			addCriterion("is_winner not between", value1, value2, "isWinner");
			return (Criteria) this;
		}

		public Criteria andIsLuckyIsNull() {
			addCriterion("is_lucky is null");
			return (Criteria) this;
		}

		public Criteria andIsLuckyIsNotNull() {
			addCriterion("is_lucky is not null");
			return (Criteria) this;
		}

		public Criteria andIsLuckyEqualTo(String value) {
			addCriterion("is_lucky =", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyNotEqualTo(String value) {
			addCriterion("is_lucky <>", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyGreaterThan(String value) {
			addCriterion("is_lucky >", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyGreaterThanOrEqualTo(String value) {
			addCriterion("is_lucky >=", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyLessThan(String value) {
			addCriterion("is_lucky <", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyLessThanOrEqualTo(String value) {
			addCriterion("is_lucky <=", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyLike(String value) {
			addCriterion("is_lucky like", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyNotLike(String value) {
			addCriterion("is_lucky not like", value, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyIn(List<String> values) {
			addCriterion("is_lucky in", values, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyNotIn(List<String> values) {
			addCriterion("is_lucky not in", values, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyBetween(String value1, String value2) {
			addCriterion("is_lucky between", value1, value2, "isLucky");
			return (Criteria) this;
		}

		public Criteria andIsLuckyNotBetween(String value1, String value2) {
			addCriterion("is_lucky not between", value1, value2, "isLucky");
			return (Criteria) this;
		}

		public Criteria andTrxIdIsNull() {
			addCriterion("trx_id is null");
			return (Criteria) this;
		}

		public Criteria andTrxIdIsNotNull() {
			addCriterion("trx_id is not null");
			return (Criteria) this;
		}

		public Criteria andTrxIdEqualTo(String value) {
			addCriterion("trx_id =", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdNotEqualTo(String value) {
			addCriterion("trx_id <>", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdGreaterThan(String value) {
			addCriterion("trx_id >", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdGreaterThanOrEqualTo(String value) {
			addCriterion("trx_id >=", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdLessThan(String value) {
			addCriterion("trx_id <", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdLessThanOrEqualTo(String value) {
			addCriterion("trx_id <=", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdLike(String value) {
			addCriterion("trx_id like", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdNotLike(String value) {
			addCriterion("trx_id not like", value, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdIn(List<String> values) {
			addCriterion("trx_id in", values, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdNotIn(List<String> values) {
			addCriterion("trx_id not in", values, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdBetween(String value1, String value2) {
			addCriterion("trx_id between", value1, value2, "trxId");
			return (Criteria) this;
		}

		public Criteria andTrxIdNotBetween(String value1, String value2) {
			addCriterion("trx_id not between", value1, value2, "trxId");
			return (Criteria) this;
		}

		public Criteria andTradeQtyIsNull() {
			addCriterion("trade_qty is null");
			return (Criteria) this;
		}

		public Criteria andTradeQtyIsNotNull() {
			addCriterion("trade_qty is not null");
			return (Criteria) this;
		}

		public Criteria andTradeQtyEqualTo(BigDecimal value) {
			addCriterion("trade_qty =", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyNotEqualTo(BigDecimal value) {
			addCriterion("trade_qty <>", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyGreaterThan(BigDecimal value) {
			addCriterion("trade_qty >", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("trade_qty >=", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyLessThan(BigDecimal value) {
			addCriterion("trade_qty <", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("trade_qty <=", value, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyIn(List<BigDecimal> values) {
			addCriterion("trade_qty in", values, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyNotIn(List<BigDecimal> values) {
			addCriterion("trade_qty not in", values, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("trade_qty between", value1, value2, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeQtyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("trade_qty not between", value1, value2, "tradeQty");
			return (Criteria) this;
		}

		public Criteria andTradeDateIsNull() {
			addCriterion("trade_date is null");
			return (Criteria) this;
		}

		public Criteria andTradeDateIsNotNull() {
			addCriterion("trade_date is not null");
			return (Criteria) this;
		}

		public Criteria andTradeDateEqualTo(Date value) {
			addCriterion("trade_date =", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateNotEqualTo(Date value) {
			addCriterion("trade_date <>", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateGreaterThan(Date value) {
			addCriterion("trade_date >", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateGreaterThanOrEqualTo(Date value) {
			addCriterion("trade_date >=", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateLessThan(Date value) {
			addCriterion("trade_date <", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateLessThanOrEqualTo(Date value) {
			addCriterion("trade_date <=", value, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateIn(List<Date> values) {
			addCriterion("trade_date in", values, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateNotIn(List<Date> values) {
			addCriterion("trade_date not in", values, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateBetween(Date value1, Date value2) {
			addCriterion("trade_date between", value1, value2, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andTradeDateNotBetween(Date value1, Date value2) {
			addCriterion("trade_date not between", value1, value2, "tradeDate");
			return (Criteria) this;
		}

		public Criteria andWinQtyIsNull() {
			addCriterion("win_qty is null");
			return (Criteria) this;
		}

		public Criteria andWinQtyIsNotNull() {
			addCriterion("win_qty is not null");
			return (Criteria) this;
		}

		public Criteria andWinQtyEqualTo(BigDecimal value) {
			addCriterion("win_qty =", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyNotEqualTo(BigDecimal value) {
			addCriterion("win_qty <>", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyGreaterThan(BigDecimal value) {
			addCriterion("win_qty >", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("win_qty >=", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyLessThan(BigDecimal value) {
			addCriterion("win_qty <", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("win_qty <=", value, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyIn(List<BigDecimal> values) {
			addCriterion("win_qty in", values, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyNotIn(List<BigDecimal> values) {
			addCriterion("win_qty not in", values, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("win_qty between", value1, value2, "winQty");
			return (Criteria) this;
		}

		public Criteria andWinQtyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("win_qty not between", value1, value2, "winQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyIsNull() {
			addCriterion("lucky_qty is null");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyIsNotNull() {
			addCriterion("lucky_qty is not null");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyEqualTo(BigDecimal value) {
			addCriterion("lucky_qty =", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyNotEqualTo(BigDecimal value) {
			addCriterion("lucky_qty <>", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyGreaterThan(BigDecimal value) {
			addCriterion("lucky_qty >", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyGreaterThanOrEqualTo(BigDecimal value) {
			addCriterion("lucky_qty >=", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyLessThan(BigDecimal value) {
			addCriterion("lucky_qty <", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyLessThanOrEqualTo(BigDecimal value) {
			addCriterion("lucky_qty <=", value, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyIn(List<BigDecimal> values) {
			addCriterion("lucky_qty in", values, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyNotIn(List<BigDecimal> values) {
			addCriterion("lucky_qty not in", values, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("lucky_qty between", value1, value2, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andLuckyQtyNotBetween(BigDecimal value1, BigDecimal value2) {
			addCriterion("lucky_qty not between", value1, value2, "luckyQty");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNull() {
			addCriterion("create_date is null");
			return (Criteria) this;
		}

		public Criteria andCreateDateIsNotNull() {
			addCriterion("create_date is not null");
			return (Criteria) this;
		}

		public Criteria andCreateDateEqualTo(Date value) {
			addCriterion("create_date =", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotEqualTo(Date value) {
			addCriterion("create_date <>", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThan(Date value) {
			addCriterion("create_date >", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("create_date >=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThan(Date value) {
			addCriterion("create_date <", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateLessThanOrEqualTo(Date value) {
			addCriterion("create_date <=", value, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateIn(List<Date> values) {
			addCriterion("create_date in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotIn(List<Date> values) {
			addCriterion("create_date not in", values, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateBetween(Date value1, Date value2) {
			addCriterion("create_date between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andCreateDateNotBetween(Date value1, Date value2) {
			addCriterion("create_date not between", value1, value2, "createDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNull() {
			addCriterion("update_date is null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIsNotNull() {
			addCriterion("update_date is not null");
			return (Criteria) this;
		}

		public Criteria andUpdateDateEqualTo(Date value) {
			addCriterion("update_date =", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotEqualTo(Date value) {
			addCriterion("update_date <>", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThan(Date value) {
			addCriterion("update_date >", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateGreaterThanOrEqualTo(Date value) {
			addCriterion("update_date >=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThan(Date value) {
			addCriterion("update_date <", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateLessThanOrEqualTo(Date value) {
			addCriterion("update_date <=", value, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateIn(List<Date> values) {
			addCriterion("update_date in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotIn(List<Date> values) {
			addCriterion("update_date not in", values, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateBetween(Date value1, Date value2) {
			addCriterion("update_date between", value1, value2, "updateDate");
			return (Criteria) this;
		}

		public Criteria andUpdateDateNotBetween(Date value1, Date value2) {
			addCriterion("update_date not between", value1, value2, "updateDate");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table activity_stage_user
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table activity_stage_user
     *
     * @mbg.generated do_not_delete_during_merge Wed Sep 19 16:10:40 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}