package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;
import java.util.Date;

public class ActivityStage implements Serializable{

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.activity_id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long activityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.status
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.start_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Date startDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.end_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Date endDate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.common_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long commonCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.common_min_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long commonMinQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.common_max_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long commonMaxQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.lucky_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long luckyCount;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.lucky_coin_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long luckyCoinQty;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.lucky_method
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String luckyMethod;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.token_name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String tokenName;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.token_contract
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String tokenContract;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.precision_number
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Integer precisionNumber;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.seq
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Integer seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.is_paid
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private String isPaid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column activity_stage.need_buy_eos
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	private Long needBuyEos;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.id
	 * @return  the value of activity_stage.id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.id
	 * @param id  the value for activity_stage.id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.activity_id
	 * @return  the value of activity_stage.activity_id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getActivityId() {
		return activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.activity_id
	 * @param activityId  the value for activity_stage.activity_id
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setActivityId(Long activityId) {
		this.activityId = activityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.name
	 * @return  the value of activity_stage.name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.name
	 * @param name  the value for activity_stage.name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.status
	 * @return  the value of activity_stage.status
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.status
	 * @param status  the value for activity_stage.status
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.start_date
	 * @return  the value of activity_stage.start_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Date getStartDate() {
		return startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.start_date
	 * @param startDate  the value for activity_stage.start_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setStartDate(Date startDate) {
		this.startDate = startDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.end_date
	 * @return  the value of activity_stage.end_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Date getEndDate() {
		return endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.end_date
	 * @param endDate  the value for activity_stage.end_date
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setEndDate(Date endDate) {
		this.endDate = endDate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.common_count
	 * @return  the value of activity_stage.common_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getCommonCount() {
		return commonCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.common_count
	 * @param commonCount  the value for activity_stage.common_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setCommonCount(Long commonCount) {
		this.commonCount = commonCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.common_min_qty
	 * @return  the value of activity_stage.common_min_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getCommonMinQty() {
		return commonMinQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.common_min_qty
	 * @param commonMinQty  the value for activity_stage.common_min_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setCommonMinQty(Long commonMinQty) {
		this.commonMinQty = commonMinQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.common_max_qty
	 * @return  the value of activity_stage.common_max_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getCommonMaxQty() {
		return commonMaxQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.common_max_qty
	 * @param commonMaxQty  the value for activity_stage.common_max_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setCommonMaxQty(Long commonMaxQty) {
		this.commonMaxQty = commonMaxQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.lucky_count
	 * @return  the value of activity_stage.lucky_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getLuckyCount() {
		return luckyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.lucky_count
	 * @param luckyCount  the value for activity_stage.lucky_count
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setLuckyCount(Long luckyCount) {
		this.luckyCount = luckyCount;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.lucky_coin_qty
	 * @return  the value of activity_stage.lucky_coin_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getLuckyCoinQty() {
		return luckyCoinQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.lucky_coin_qty
	 * @param luckyCoinQty  the value for activity_stage.lucky_coin_qty
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setLuckyCoinQty(Long luckyCoinQty) {
		this.luckyCoinQty = luckyCoinQty;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.lucky_method
	 * @return  the value of activity_stage.lucky_method
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getLuckyMethod() {
		return luckyMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.lucky_method
	 * @param luckyMethod  the value for activity_stage.lucky_method
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setLuckyMethod(String luckyMethod) {
		this.luckyMethod = luckyMethod;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.token_name
	 * @return  the value of activity_stage.token_name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getTokenName() {
		return tokenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.token_name
	 * @param tokenName  the value for activity_stage.token_name
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setTokenName(String tokenName) {
		this.tokenName = tokenName;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.token_contract
	 * @return  the value of activity_stage.token_contract
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getTokenContract() {
		return tokenContract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.token_contract
	 * @param tokenContract  the value for activity_stage.token_contract
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setTokenContract(String tokenContract) {
		this.tokenContract = tokenContract;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.precision_number
	 * @return  the value of activity_stage.precision_number
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Integer getPrecisionNumber() {
		return precisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.precision_number
	 * @param precisionNumber  the value for activity_stage.precision_number
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setPrecisionNumber(Integer precisionNumber) {
		this.precisionNumber = precisionNumber;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.seq
	 * @return  the value of activity_stage.seq
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Integer getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.seq
	 * @param seq  the value for activity_stage.seq
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setSeq(Integer seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.is_paid
	 * @return  the value of activity_stage.is_paid
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public String getIsPaid() {
		return isPaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.is_paid
	 * @param isPaid  the value for activity_stage.is_paid
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setIsPaid(String isPaid) {
		this.isPaid = isPaid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column activity_stage.need_buy_eos
	 * @return  the value of activity_stage.need_buy_eos
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public Long getNeedBuyEos() {
		return needBuyEos;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column activity_stage.need_buy_eos
	 * @param needBuyEos  the value for activity_stage.need_buy_eos
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	public void setNeedBuyEos(Long needBuyEos) {
		this.needBuyEos = needBuyEos;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = 4835267146270847755L;
}