package it.etoken.base.model.eosblock.entity;

import java.io.Serializable;
import java.util.Date;

public class UserEosAccount implements Serializable{
    /**
	 * 
	 */
	private static final long serialVersionUID = 4347505841541516244L;

	/**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_eos_account.id
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_eos_account.uid
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    private Long uid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_eos_account.eos_account
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    private String eosAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_eos_account.create_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    private Date createDate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_eos_account.update_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    private Date updateDate;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_eos_account.id
     *
     * @return the value of user_eos_account.id
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_eos_account.id
     *
     * @param id the value for user_eos_account.id
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_eos_account.uid
     *
     * @return the value of user_eos_account.uid
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public Long getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_eos_account.uid
     *
     * @param uid the value for user_eos_account.uid
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public void setUid(Long uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_eos_account.eos_account
     *
     * @return the value of user_eos_account.eos_account
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public String getEosAccount() {
        return eosAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_eos_account.eos_account
     *
     * @param eosAccount the value for user_eos_account.eos_account
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public void setEosAccount(String eosAccount) {
        this.eosAccount = eosAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_eos_account.create_date
     *
     * @return the value of user_eos_account.create_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public Date getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_eos_account.create_date
     *
     * @param createDate the value for user_eos_account.create_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_eos_account.update_date
     *
     * @return the value of user_eos_account.update_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public Date getUpdateDate() {
        return updateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_eos_account.update_date
     *
     * @param updateDate the value for user_eos_account.update_date
     *
     * @mbg.generated Wed Sep 12 15:04:47 CST 2018
     */
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }
}