package it.etoken.base.model.user.entity;

import java.io.Serializable;
import java.util.Date;

public class Sysconf implements Serializable{
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.id
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.name
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.description
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.value
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private String value;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.createdate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private Date createdate;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sysconf.modifydate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	private Date modifydate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.id
	 * @return  the value of sysconf.id
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.id
	 * @param id  the value for sysconf.id
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.name
	 * @return  the value of sysconf.name
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.name
	 * @param name  the value for sysconf.name
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.description
	 * @return  the value of sysconf.description
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.description
	 * @param description  the value for sysconf.description
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.value
	 * @return  the value of sysconf.value
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public String getValue() {
		return value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.value
	 * @param value  the value for sysconf.value
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setValue(String value) {
		this.value = value;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.createdate
	 * @return  the value of sysconf.createdate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public Date getCreatedate() {
		return createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.createdate
	 * @param createdate  the value for sysconf.createdate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setCreatedate(Date createdate) {
		this.createdate = createdate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sysconf.modifydate
	 * @return  the value of sysconf.modifydate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sysconf.modifydate
	 * @param modifydate  the value for sysconf.modifydate
	 * @mbg.generated  Thu Oct 18 19:43:29 CST 2018
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -4467978331739201343L;
}