package it.etoken.base.model.market.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class CoinsExample {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	protected String orderByClause;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	protected boolean distinct;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	protected List<Criteria> oredCriteria;

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public CoinsExample() {
		oredCriteria = new ArrayList<Criteria>();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public void setOrderByClause(String orderByClause) {
		this.orderByClause = orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public String getOrderByClause() {
		return orderByClause;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public void setDistinct(boolean distinct) {
		this.distinct = distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public boolean isDistinct() {
		return distinct;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public List<Criteria> getOredCriteria() {
		return oredCriteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public void or(Criteria criteria) {
		oredCriteria.add(criteria);
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public Criteria or() {
		Criteria criteria = createCriteriaInternal();
		oredCriteria.add(criteria);
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public Criteria createCriteria() {
		Criteria criteria = createCriteriaInternal();
		if (oredCriteria.size() == 0) {
			oredCriteria.add(criteria);
		}
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	protected Criteria createCriteriaInternal() {
		Criteria criteria = new Criteria();
		return criteria;
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public void clear() {
		oredCriteria.clear();
		orderByClause = null;
		distinct = false;
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	protected abstract static class GeneratedCriteria {
		protected List<Criterion> criteria;

		protected GeneratedCriteria() {
			super();
			criteria = new ArrayList<Criterion>();
		}

		public boolean isValid() {
			return criteria.size() > 0;
		}

		public List<Criterion> getAllCriteria() {
			return criteria;
		}

		public List<Criterion> getCriteria() {
			return criteria;
		}

		protected void addCriterion(String condition) {
			if (condition == null) {
				throw new RuntimeException("Value for condition cannot be null");
			}
			criteria.add(new Criterion(condition));
		}

		protected void addCriterion(String condition, Object value, String property) {
			if (value == null) {
				throw new RuntimeException("Value for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value));
		}

		protected void addCriterion(String condition, Object value1, Object value2, String property) {
			if (value1 == null || value2 == null) {
				throw new RuntimeException("Between values for " + property + " cannot be null");
			}
			criteria.add(new Criterion(condition, value1, value2));
		}

		public Criteria andIdIsNull() {
			addCriterion("id is null");
			return (Criteria) this;
		}

		public Criteria andIdIsNotNull() {
			addCriterion("id is not null");
			return (Criteria) this;
		}

		public Criteria andIdEqualTo(Long value) {
			addCriterion("id =", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotEqualTo(Long value) {
			addCriterion("id <>", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThan(Long value) {
			addCriterion("id >", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdGreaterThanOrEqualTo(Long value) {
			addCriterion("id >=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThan(Long value) {
			addCriterion("id <", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdLessThanOrEqualTo(Long value) {
			addCriterion("id <=", value, "id");
			return (Criteria) this;
		}

		public Criteria andIdIn(List<Long> values) {
			addCriterion("id in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotIn(List<Long> values) {
			addCriterion("id not in", values, "id");
			return (Criteria) this;
		}

		public Criteria andIdBetween(Long value1, Long value2) {
			addCriterion("id between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andIdNotBetween(Long value1, Long value2) {
			addCriterion("id not between", value1, value2, "id");
			return (Criteria) this;
		}

		public Criteria andNameIsNull() {
			addCriterion("name is null");
			return (Criteria) this;
		}

		public Criteria andNameIsNotNull() {
			addCriterion("name is not null");
			return (Criteria) this;
		}

		public Criteria andNameEqualTo(String value) {
			addCriterion("name =", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotEqualTo(String value) {
			addCriterion("name <>", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThan(String value) {
			addCriterion("name >", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameGreaterThanOrEqualTo(String value) {
			addCriterion("name >=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThan(String value) {
			addCriterion("name <", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLessThanOrEqualTo(String value) {
			addCriterion("name <=", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameLike(String value) {
			addCriterion("name like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotLike(String value) {
			addCriterion("name not like", value, "name");
			return (Criteria) this;
		}

		public Criteria andNameIn(List<String> values) {
			addCriterion("name in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotIn(List<String> values) {
			addCriterion("name not in", values, "name");
			return (Criteria) this;
		}

		public Criteria andNameBetween(String value1, String value2) {
			addCriterion("name between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andNameNotBetween(String value1, String value2) {
			addCriterion("name not between", value1, value2, "name");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNull() {
			addCriterion("createdate is null");
			return (Criteria) this;
		}

		public Criteria andCreatedateIsNotNull() {
			addCriterion("createdate is not null");
			return (Criteria) this;
		}

		public Criteria andCreatedateEqualTo(Date value) {
			addCriterion("createdate =", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotEqualTo(Date value) {
			addCriterion("createdate <>", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThan(Date value) {
			addCriterion("createdate >", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateGreaterThanOrEqualTo(Date value) {
			addCriterion("createdate >=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThan(Date value) {
			addCriterion("createdate <", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateLessThanOrEqualTo(Date value) {
			addCriterion("createdate <=", value, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateIn(List<Date> values) {
			addCriterion("createdate in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotIn(List<Date> values) {
			addCriterion("createdate not in", values, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateBetween(Date value1, Date value2) {
			addCriterion("createdate between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andCreatedateNotBetween(Date value1, Date value2) {
			addCriterion("createdate not between", value1, value2, "createdate");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNull() {
			addCriterion("modifydate is null");
			return (Criteria) this;
		}

		public Criteria andModifydateIsNotNull() {
			addCriterion("modifydate is not null");
			return (Criteria) this;
		}

		public Criteria andModifydateEqualTo(Date value) {
			addCriterion("modifydate =", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotEqualTo(Date value) {
			addCriterion("modifydate <>", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThan(Date value) {
			addCriterion("modifydate >", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateGreaterThanOrEqualTo(Date value) {
			addCriterion("modifydate >=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThan(Date value) {
			addCriterion("modifydate <", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateLessThanOrEqualTo(Date value) {
			addCriterion("modifydate <=", value, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateIn(List<Date> values) {
			addCriterion("modifydate in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotIn(List<Date> values) {
			addCriterion("modifydate not in", values, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateBetween(Date value1, Date value2) {
			addCriterion("modifydate between", value1, value2, "modifydate");
			return (Criteria) this;
		}

		public Criteria andModifydateNotBetween(Date value1, Date value2) {
			addCriterion("modifydate not between", value1, value2, "modifydate");
			return (Criteria) this;
		}

		public Criteria andSiteIsNull() {
			addCriterion("site is null");
			return (Criteria) this;
		}

		public Criteria andSiteIsNotNull() {
			addCriterion("site is not null");
			return (Criteria) this;
		}

		public Criteria andSiteEqualTo(String value) {
			addCriterion("site =", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotEqualTo(String value) {
			addCriterion("site <>", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThan(String value) {
			addCriterion("site >", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteGreaterThanOrEqualTo(String value) {
			addCriterion("site >=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThan(String value) {
			addCriterion("site <", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLessThanOrEqualTo(String value) {
			addCriterion("site <=", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteLike(String value) {
			addCriterion("site like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotLike(String value) {
			addCriterion("site not like", value, "site");
			return (Criteria) this;
		}

		public Criteria andSiteIn(List<String> values) {
			addCriterion("site in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotIn(List<String> values) {
			addCriterion("site not in", values, "site");
			return (Criteria) this;
		}

		public Criteria andSiteBetween(String value1, String value2) {
			addCriterion("site between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andSiteNotBetween(String value1, String value2) {
			addCriterion("site not between", value1, value2, "site");
			return (Criteria) this;
		}

		public Criteria andImgIsNull() {
			addCriterion("img is null");
			return (Criteria) this;
		}

		public Criteria andImgIsNotNull() {
			addCriterion("img is not null");
			return (Criteria) this;
		}

		public Criteria andImgEqualTo(String value) {
			addCriterion("img =", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotEqualTo(String value) {
			addCriterion("img <>", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThan(String value) {
			addCriterion("img >", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgGreaterThanOrEqualTo(String value) {
			addCriterion("img >=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThan(String value) {
			addCriterion("img <", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLessThanOrEqualTo(String value) {
			addCriterion("img <=", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgLike(String value) {
			addCriterion("img like", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotLike(String value) {
			addCriterion("img not like", value, "img");
			return (Criteria) this;
		}

		public Criteria andImgIn(List<String> values) {
			addCriterion("img in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotIn(List<String> values) {
			addCriterion("img not in", values, "img");
			return (Criteria) this;
		}

		public Criteria andImgBetween(String value1, String value2) {
			addCriterion("img between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andImgNotBetween(String value1, String value2) {
			addCriterion("img not between", value1, value2, "img");
			return (Criteria) this;
		}

		public Criteria andTagIsNull() {
			addCriterion("tag is null");
			return (Criteria) this;
		}

		public Criteria andTagIsNotNull() {
			addCriterion("tag is not null");
			return (Criteria) this;
		}

		public Criteria andTagEqualTo(String value) {
			addCriterion("tag =", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotEqualTo(String value) {
			addCriterion("tag <>", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThan(String value) {
			addCriterion("tag >", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagGreaterThanOrEqualTo(String value) {
			addCriterion("tag >=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThan(String value) {
			addCriterion("tag <", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLessThanOrEqualTo(String value) {
			addCriterion("tag <=", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagLike(String value) {
			addCriterion("tag like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotLike(String value) {
			addCriterion("tag not like", value, "tag");
			return (Criteria) this;
		}

		public Criteria andTagIn(List<String> values) {
			addCriterion("tag in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotIn(List<String> values) {
			addCriterion("tag not in", values, "tag");
			return (Criteria) this;
		}

		public Criteria andTagBetween(String value1, String value2) {
			addCriterion("tag between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTagNotBetween(String value1, String value2) {
			addCriterion("tag not between", value1, value2, "tag");
			return (Criteria) this;
		}

		public Criteria andTotalIsNull() {
			addCriterion("total is null");
			return (Criteria) this;
		}

		public Criteria andTotalIsNotNull() {
			addCriterion("total is not null");
			return (Criteria) this;
		}

		public Criteria andTotalEqualTo(Long value) {
			addCriterion("total =", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalNotEqualTo(Long value) {
			addCriterion("total <>", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalGreaterThan(Long value) {
			addCriterion("total >", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalGreaterThanOrEqualTo(Long value) {
			addCriterion("total >=", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalLessThan(Long value) {
			addCriterion("total <", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalLessThanOrEqualTo(Long value) {
			addCriterion("total <=", value, "total");
			return (Criteria) this;
		}

		public Criteria andTotalIn(List<Long> values) {
			addCriterion("total in", values, "total");
			return (Criteria) this;
		}

		public Criteria andTotalNotIn(List<Long> values) {
			addCriterion("total not in", values, "total");
			return (Criteria) this;
		}

		public Criteria andTotalBetween(Long value1, Long value2) {
			addCriterion("total between", value1, value2, "total");
			return (Criteria) this;
		}

		public Criteria andTotalNotBetween(Long value1, Long value2) {
			addCriterion("total not between", value1, value2, "total");
			return (Criteria) this;
		}

		public Criteria andMarkeIsNull() {
			addCriterion("marke is null");
			return (Criteria) this;
		}

		public Criteria andMarkeIsNotNull() {
			addCriterion("marke is not null");
			return (Criteria) this;
		}

		public Criteria andMarkeEqualTo(Long value) {
			addCriterion("marke =", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeNotEqualTo(Long value) {
			addCriterion("marke <>", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeGreaterThan(Long value) {
			addCriterion("marke >", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeGreaterThanOrEqualTo(Long value) {
			addCriterion("marke >=", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeLessThan(Long value) {
			addCriterion("marke <", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeLessThanOrEqualTo(Long value) {
			addCriterion("marke <=", value, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeIn(List<Long> values) {
			addCriterion("marke in", values, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeNotIn(List<Long> values) {
			addCriterion("marke not in", values, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeBetween(Long value1, Long value2) {
			addCriterion("marke between", value1, value2, "marke");
			return (Criteria) this;
		}

		public Criteria andMarkeNotBetween(Long value1, Long value2) {
			addCriterion("marke not between", value1, value2, "marke");
			return (Criteria) this;
		}

		public Criteria andCodeIsNull() {
			addCriterion("code is null");
			return (Criteria) this;
		}

		public Criteria andCodeIsNotNull() {
			addCriterion("code is not null");
			return (Criteria) this;
		}

		public Criteria andCodeEqualTo(String value) {
			addCriterion("code =", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotEqualTo(String value) {
			addCriterion("code <>", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThan(String value) {
			addCriterion("code >", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeGreaterThanOrEqualTo(String value) {
			addCriterion("code >=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThan(String value) {
			addCriterion("code <", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLessThanOrEqualTo(String value) {
			addCriterion("code <=", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeLike(String value) {
			addCriterion("code like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotLike(String value) {
			addCriterion("code not like", value, "code");
			return (Criteria) this;
		}

		public Criteria andCodeIn(List<String> values) {
			addCriterion("code in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotIn(List<String> values) {
			addCriterion("code not in", values, "code");
			return (Criteria) this;
		}

		public Criteria andCodeBetween(String value1, String value2) {
			addCriterion("code between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andCodeNotBetween(String value1, String value2) {
			addCriterion("code not between", value1, value2, "code");
			return (Criteria) this;
		}

		public Criteria andSymbleIsNull() {
			addCriterion("symble is null");
			return (Criteria) this;
		}

		public Criteria andSymbleIsNotNull() {
			addCriterion("symble is not null");
			return (Criteria) this;
		}

		public Criteria andSymbleEqualTo(String value) {
			addCriterion("symble =", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleNotEqualTo(String value) {
			addCriterion("symble <>", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleGreaterThan(String value) {
			addCriterion("symble >", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleGreaterThanOrEqualTo(String value) {
			addCriterion("symble >=", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleLessThan(String value) {
			addCriterion("symble <", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleLessThanOrEqualTo(String value) {
			addCriterion("symble <=", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleLike(String value) {
			addCriterion("symble like", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleNotLike(String value) {
			addCriterion("symble not like", value, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleIn(List<String> values) {
			addCriterion("symble in", values, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleNotIn(List<String> values) {
			addCriterion("symble not in", values, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleBetween(String value1, String value2) {
			addCriterion("symble between", value1, value2, "symble");
			return (Criteria) this;
		}

		public Criteria andSymbleNotBetween(String value1, String value2) {
			addCriterion("symble not between", value1, value2, "symble");
			return (Criteria) this;
		}

		public Criteria andContractAccountIsNull() {
			addCriterion("contract_account is null");
			return (Criteria) this;
		}

		public Criteria andContractAccountIsNotNull() {
			addCriterion("contract_account is not null");
			return (Criteria) this;
		}

		public Criteria andContractAccountEqualTo(String value) {
			addCriterion("contract_account =", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountNotEqualTo(String value) {
			addCriterion("contract_account <>", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountGreaterThan(String value) {
			addCriterion("contract_account >", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountGreaterThanOrEqualTo(String value) {
			addCriterion("contract_account >=", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountLessThan(String value) {
			addCriterion("contract_account <", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountLessThanOrEqualTo(String value) {
			addCriterion("contract_account <=", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountLike(String value) {
			addCriterion("contract_account like", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountNotLike(String value) {
			addCriterion("contract_account not like", value, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountIn(List<String> values) {
			addCriterion("contract_account in", values, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountNotIn(List<String> values) {
			addCriterion("contract_account not in", values, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountBetween(String value1, String value2) {
			addCriterion("contract_account between", value1, value2, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andContractAccountNotBetween(String value1, String value2) {
			addCriterion("contract_account not between", value1, value2, "contractAccount");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketIsNull() {
			addCriterion("is_support_market is null");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketIsNotNull() {
			addCriterion("is_support_market is not null");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketEqualTo(String value) {
			addCriterion("is_support_market =", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketNotEqualTo(String value) {
			addCriterion("is_support_market <>", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketGreaterThan(String value) {
			addCriterion("is_support_market >", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketGreaterThanOrEqualTo(String value) {
			addCriterion("is_support_market >=", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketLessThan(String value) {
			addCriterion("is_support_market <", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketLessThanOrEqualTo(String value) {
			addCriterion("is_support_market <=", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketLike(String value) {
			addCriterion("is_support_market like", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketNotLike(String value) {
			addCriterion("is_support_market not like", value, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketIn(List<String> values) {
			addCriterion("is_support_market in", values, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketNotIn(List<String> values) {
			addCriterion("is_support_market not in", values, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketBetween(String value1, String value2) {
			addCriterion("is_support_market between", value1, value2, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andIsSupportMarketNotBetween(String value1, String value2) {
			addCriterion("is_support_market not between", value1, value2, "isSupportMarket");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNull() {
			addCriterion("precision_number is null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIsNotNull() {
			addCriterion("precision_number is not null");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberEqualTo(Integer value) {
			addCriterion("precision_number =", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotEqualTo(Integer value) {
			addCriterion("precision_number <>", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThan(Integer value) {
			addCriterion("precision_number >", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberGreaterThanOrEqualTo(Integer value) {
			addCriterion("precision_number >=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThan(Integer value) {
			addCriterion("precision_number <", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberLessThanOrEqualTo(Integer value) {
			addCriterion("precision_number <=", value, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberIn(List<Integer> values) {
			addCriterion("precision_number in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotIn(List<Integer> values) {
			addCriterion("precision_number not in", values, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberBetween(Integer value1, Integer value2) {
			addCriterion("precision_number between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andPrecisionNumberNotBetween(Integer value1, Integer value2) {
			addCriterion("precision_number not between", value1, value2, "precisionNumber");
			return (Criteria) this;
		}

		public Criteria andIssueDateIsNull() {
			addCriterion("issue_date is null");
			return (Criteria) this;
		}

		public Criteria andIssueDateIsNotNull() {
			addCriterion("issue_date is not null");
			return (Criteria) this;
		}

		public Criteria andIssueDateEqualTo(Date value) {
			addCriterion("issue_date =", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotEqualTo(Date value) {
			addCriterion("issue_date <>", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateGreaterThan(Date value) {
			addCriterion("issue_date >", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateGreaterThanOrEqualTo(Date value) {
			addCriterion("issue_date >=", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateLessThan(Date value) {
			addCriterion("issue_date <", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateLessThanOrEqualTo(Date value) {
			addCriterion("issue_date <=", value, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateIn(List<Date> values) {
			addCriterion("issue_date in", values, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotIn(List<Date> values) {
			addCriterion("issue_date not in", values, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateBetween(Date value1, Date value2) {
			addCriterion("issue_date between", value1, value2, "issueDate");
			return (Criteria) this;
		}

		public Criteria andIssueDateNotBetween(Date value1, Date value2) {
			addCriterion("issue_date not between", value1, value2, "issueDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceIsNull() {
			addCriterion("crowdfunding_price is null");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceIsNotNull() {
			addCriterion("crowdfunding_price is not null");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceEqualTo(String value) {
			addCriterion("crowdfunding_price =", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceNotEqualTo(String value) {
			addCriterion("crowdfunding_price <>", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceGreaterThan(String value) {
			addCriterion("crowdfunding_price >", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceGreaterThanOrEqualTo(String value) {
			addCriterion("crowdfunding_price >=", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceLessThan(String value) {
			addCriterion("crowdfunding_price <", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceLessThanOrEqualTo(String value) {
			addCriterion("crowdfunding_price <=", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceLike(String value) {
			addCriterion("crowdfunding_price like", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceNotLike(String value) {
			addCriterion("crowdfunding_price not like", value, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceIn(List<String> values) {
			addCriterion("crowdfunding_price in", values, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceNotIn(List<String> values) {
			addCriterion("crowdfunding_price not in", values, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceBetween(String value1, String value2) {
			addCriterion("crowdfunding_price between", value1, value2, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingPriceNotBetween(String value1, String value2) {
			addCriterion("crowdfunding_price not between", value1, value2, "crowdfundingPrice");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlIsNull() {
			addCriterion("white_paper_url is null");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlIsNotNull() {
			addCriterion("white_paper_url is not null");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlEqualTo(String value) {
			addCriterion("white_paper_url =", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlNotEqualTo(String value) {
			addCriterion("white_paper_url <>", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlGreaterThan(String value) {
			addCriterion("white_paper_url >", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlGreaterThanOrEqualTo(String value) {
			addCriterion("white_paper_url >=", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlLessThan(String value) {
			addCriterion("white_paper_url <", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlLessThanOrEqualTo(String value) {
			addCriterion("white_paper_url <=", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlLike(String value) {
			addCriterion("white_paper_url like", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlNotLike(String value) {
			addCriterion("white_paper_url not like", value, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlIn(List<String> values) {
			addCriterion("white_paper_url in", values, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlNotIn(List<String> values) {
			addCriterion("white_paper_url not in", values, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlBetween(String value1, String value2) {
			addCriterion("white_paper_url between", value1, value2, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andWhitePaperUrlNotBetween(String value1, String value2) {
			addCriterion("white_paper_url not between", value1, value2, "whitePaperUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlIsNull() {
			addCriterion("block_query_url is null");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlIsNotNull() {
			addCriterion("block_query_url is not null");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlEqualTo(String value) {
			addCriterion("block_query_url =", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlNotEqualTo(String value) {
			addCriterion("block_query_url <>", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlGreaterThan(String value) {
			addCriterion("block_query_url >", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlGreaterThanOrEqualTo(String value) {
			addCriterion("block_query_url >=", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlLessThan(String value) {
			addCriterion("block_query_url <", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlLessThanOrEqualTo(String value) {
			addCriterion("block_query_url <=", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlLike(String value) {
			addCriterion("block_query_url like", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlNotLike(String value) {
			addCriterion("block_query_url not like", value, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlIn(List<String> values) {
			addCriterion("block_query_url in", values, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlNotIn(List<String> values) {
			addCriterion("block_query_url not in", values, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlBetween(String value1, String value2) {
			addCriterion("block_query_url between", value1, value2, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andBlockQueryUrlNotBetween(String value1, String value2) {
			addCriterion("block_query_url not between", value1, value2, "blockQueryUrl");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelIsNull() {
			addCriterion("recommend_level is null");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelIsNotNull() {
			addCriterion("recommend_level is not null");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelEqualTo(Integer value) {
			addCriterion("recommend_level =", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelNotEqualTo(Integer value) {
			addCriterion("recommend_level <>", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelGreaterThan(Integer value) {
			addCriterion("recommend_level >", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelGreaterThanOrEqualTo(Integer value) {
			addCriterion("recommend_level >=", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelLessThan(Integer value) {
			addCriterion("recommend_level <", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelLessThanOrEqualTo(Integer value) {
			addCriterion("recommend_level <=", value, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelIn(List<Integer> values) {
			addCriterion("recommend_level in", values, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelNotIn(List<Integer> values) {
			addCriterion("recommend_level not in", values, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelBetween(Integer value1, Integer value2) {
			addCriterion("recommend_level between", value1, value2, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andRecommendLevelNotBetween(Integer value1, Integer value2) {
			addCriterion("recommend_level not between", value1, value2, "recommendLevel");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeIsNull() {
			addCriterion("project_creative is null");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeIsNotNull() {
			addCriterion("project_creative is not null");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeEqualTo(String value) {
			addCriterion("project_creative =", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeNotEqualTo(String value) {
			addCriterion("project_creative <>", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeGreaterThan(String value) {
			addCriterion("project_creative >", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeGreaterThanOrEqualTo(String value) {
			addCriterion("project_creative >=", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeLessThan(String value) {
			addCriterion("project_creative <", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeLessThanOrEqualTo(String value) {
			addCriterion("project_creative <=", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeLike(String value) {
			addCriterion("project_creative like", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeNotLike(String value) {
			addCriterion("project_creative not like", value, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeIn(List<String> values) {
			addCriterion("project_creative in", values, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeNotIn(List<String> values) {
			addCriterion("project_creative not in", values, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeBetween(String value1, String value2) {
			addCriterion("project_creative between", value1, value2, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andProjectCreativeNotBetween(String value1, String value2) {
			addCriterion("project_creative not between", value1, value2, "projectCreative");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueIsNull() {
			addCriterion("investment_value is null");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueIsNotNull() {
			addCriterion("investment_value is not null");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueEqualTo(String value) {
			addCriterion("investment_value =", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueNotEqualTo(String value) {
			addCriterion("investment_value <>", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueGreaterThan(String value) {
			addCriterion("investment_value >", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueGreaterThanOrEqualTo(String value) {
			addCriterion("investment_value >=", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueLessThan(String value) {
			addCriterion("investment_value <", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueLessThanOrEqualTo(String value) {
			addCriterion("investment_value <=", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueLike(String value) {
			addCriterion("investment_value like", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueNotLike(String value) {
			addCriterion("investment_value not like", value, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueIn(List<String> values) {
			addCriterion("investment_value in", values, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueNotIn(List<String> values) {
			addCriterion("investment_value not in", values, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueBetween(String value1, String value2) {
			addCriterion("investment_value between", value1, value2, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andInvestmentValueNotBetween(String value1, String value2) {
			addCriterion("investment_value not between", value1, value2, "investmentValue");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateIsNull() {
			addCriterion("crowdfunding_date is null");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateIsNotNull() {
			addCriterion("crowdfunding_date is not null");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateEqualTo(String value) {
			addCriterion("crowdfunding_date =", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateNotEqualTo(String value) {
			addCriterion("crowdfunding_date <>", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateGreaterThan(String value) {
			addCriterion("crowdfunding_date >", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateGreaterThanOrEqualTo(String value) {
			addCriterion("crowdfunding_date >=", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateLessThan(String value) {
			addCriterion("crowdfunding_date <", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateLessThanOrEqualTo(String value) {
			addCriterion("crowdfunding_date <=", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateLike(String value) {
			addCriterion("crowdfunding_date like", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateNotLike(String value) {
			addCriterion("crowdfunding_date not like", value, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateIn(List<String> values) {
			addCriterion("crowdfunding_date in", values, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateNotIn(List<String> values) {
			addCriterion("crowdfunding_date not in", values, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateBetween(String value1, String value2) {
			addCriterion("crowdfunding_date between", value1, value2, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andCrowdfundingDateNotBetween(String value1, String value2) {
			addCriterion("crowdfunding_date not between", value1, value2, "crowdfundingDate");
			return (Criteria) this;
		}

		public Criteria andExchangeIsNull() {
			addCriterion("exchange is null");
			return (Criteria) this;
		}

		public Criteria andExchangeIsNotNull() {
			addCriterion("exchange is not null");
			return (Criteria) this;
		}

		public Criteria andExchangeEqualTo(String value) {
			addCriterion("exchange =", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeNotEqualTo(String value) {
			addCriterion("exchange <>", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeGreaterThan(String value) {
			addCriterion("exchange >", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeGreaterThanOrEqualTo(String value) {
			addCriterion("exchange >=", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeLessThan(String value) {
			addCriterion("exchange <", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeLessThanOrEqualTo(String value) {
			addCriterion("exchange <=", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeLike(String value) {
			addCriterion("exchange like", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeNotLike(String value) {
			addCriterion("exchange not like", value, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeIn(List<String> values) {
			addCriterion("exchange in", values, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeNotIn(List<String> values) {
			addCriterion("exchange not in", values, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeBetween(String value1, String value2) {
			addCriterion("exchange between", value1, value2, "exchange");
			return (Criteria) this;
		}

		public Criteria andExchangeNotBetween(String value1, String value2) {
			addCriterion("exchange not between", value1, value2, "exchange");
			return (Criteria) this;
		}
	}

	/**
	 * This class was generated by MyBatis Generator. This class corresponds to the database table coins
	 * @mbg.generated  Tue Oct 16 09:41:18 CST 2018
	 */
	public static class Criterion {
		private String condition;
		private Object value;
		private Object secondValue;
		private boolean noValue;
		private boolean singleValue;
		private boolean betweenValue;
		private boolean listValue;
		private String typeHandler;

		public String getCondition() {
			return condition;
		}

		public Object getValue() {
			return value;
		}

		public Object getSecondValue() {
			return secondValue;
		}

		public boolean isNoValue() {
			return noValue;
		}

		public boolean isSingleValue() {
			return singleValue;
		}

		public boolean isBetweenValue() {
			return betweenValue;
		}

		public boolean isListValue() {
			return listValue;
		}

		public String getTypeHandler() {
			return typeHandler;
		}

		protected Criterion(String condition) {
			super();
			this.condition = condition;
			this.typeHandler = null;
			this.noValue = true;
		}

		protected Criterion(String condition, Object value, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.typeHandler = typeHandler;
			if (value instanceof List<?>) {
				this.listValue = true;
			} else {
				this.singleValue = true;
			}
		}

		protected Criterion(String condition, Object value) {
			this(condition, value, null);
		}

		protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
			super();
			this.condition = condition;
			this.value = value;
			this.secondValue = secondValue;
			this.typeHandler = typeHandler;
			this.betweenValue = true;
		}

		protected Criterion(String condition, Object value, Object secondValue) {
			this(condition, value, secondValue, null);
		}
	}

	/**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table coins
     *
     * @mbg.generated do_not_delete_during_merge Mon Jul 02 20:08:32 CST 2018
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }
}