package it.etoken.component.news.dao.mapper;

import it.etoken.base.model.news.entity.SysNotification;
import it.etoken.base.model.news.entity.SysNotificationExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface SysNotificationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@SelectProvider(type = SysNotificationSqlProvider.class, method = "countByExample")
	long countByExample(SysNotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@DeleteProvider(type = SysNotificationSqlProvider.class, method = "deleteByExample")
	int deleteByExample(SysNotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@Delete({ "delete from sys_notification", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@Insert({ "insert into sys_notification (id, picurl, ", "url, status, seq, ", "starttime, endtime, ",
			"createtime, modifydate, ", "description)", "values (#{id,jdbcType=BIGINT}, #{picurl,jdbcType=VARCHAR}, ",
			"#{url,jdbcType=VARCHAR}, #{status,jdbcType=VARCHAR}, #{seq,jdbcType=BIGINT}, ",
			"#{starttime,jdbcType=TIMESTAMP}, #{endtime,jdbcType=TIMESTAMP}, ",
			"#{createtime,jdbcType=TIMESTAMP}, #{modifydate,jdbcType=TIMESTAMP}, ",
			"#{description,jdbcType=VARCHAR})" })
	int insert(SysNotification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@InsertProvider(type = SysNotificationSqlProvider.class, method = "insertSelective")
	int insertSelective(SysNotification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@SelectProvider(type = SysNotificationSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "picurl", property = "picurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT),
			@Result(column = "starttime", property = "starttime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "endtime", property = "endtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "createtime", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modifydate", property = "modifydate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR) })
	List<SysNotification> selectByExample(SysNotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@Select({ "select", "id, picurl, url, status, seq, starttime, endtime, createtime, modifydate, description",
			"from sys_notification", "where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "picurl", property = "picurl", jdbcType = JdbcType.VARCHAR),
			@Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT),
			@Result(column = "starttime", property = "starttime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "endtime", property = "endtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "createtime", property = "createtime", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "modifydate", property = "modifydate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR) })
	SysNotification selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@UpdateProvider(type = SysNotificationSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") SysNotification record,
			@Param("example") SysNotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@UpdateProvider(type = SysNotificationSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") SysNotification record, @Param("example") SysNotificationExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@UpdateProvider(type = SysNotificationSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(SysNotification record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	@Update({ "update sys_notification", "set picurl = #{picurl,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
			"status = #{status,jdbcType=VARCHAR},", "seq = #{seq,jdbcType=BIGINT},",
			"starttime = #{starttime,jdbcType=TIMESTAMP},", "endtime = #{endtime,jdbcType=TIMESTAMP},",
			"createtime = #{createtime,jdbcType=TIMESTAMP},", "modifydate = #{modifydate,jdbcType=TIMESTAMP},",
			"description = #{description,jdbcType=VARCHAR}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(SysNotification record);
}