package it.etoken.component.news.dao.mapper;

import it.etoken.base.model.news.entity.SysNotification;
import it.etoken.base.model.news.entity.SysNotificationExample.Criteria;
import it.etoken.base.model.news.entity.SysNotificationExample.Criterion;
import it.etoken.base.model.news.entity.SysNotificationExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class SysNotificationSqlProvider {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String countByExample(SysNotificationExample example) {
		SQL sql = new SQL();
		sql.SELECT("count(*)").FROM("sys_notification");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String deleteByExample(SysNotificationExample example) {
		SQL sql = new SQL();
		sql.DELETE_FROM("sys_notification");
		applyWhere(sql, example, false);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String insertSelective(SysNotification record) {
		SQL sql = new SQL();
		sql.INSERT_INTO("sys_notification");
		if (record.getId() != null) {
			sql.VALUES("id", "#{id,jdbcType=BIGINT}");
		}
		if (record.getPicurl() != null) {
			sql.VALUES("picurl", "#{picurl,jdbcType=VARCHAR}");
		}
		if (record.getUrl() != null) {
			sql.VALUES("url", "#{url,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			sql.VALUES("status", "#{status,jdbcType=VARCHAR}");
		}
		if (record.getSeq() != null) {
			sql.VALUES("seq", "#{seq,jdbcType=BIGINT}");
		}
		if (record.getStarttime() != null) {
			sql.VALUES("starttime", "#{starttime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndtime() != null) {
			sql.VALUES("endtime", "#{endtime,jdbcType=TIMESTAMP}");
		}
		if (record.getCreatetime() != null) {
			sql.VALUES("createtime", "#{createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.VALUES("modifydate", "#{modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getDescription() != null) {
			sql.VALUES("description", "#{description,jdbcType=VARCHAR}");
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String selectByExample(SysNotificationExample example) {
		SQL sql = new SQL();
		if (example != null && example.isDistinct()) {
			sql.SELECT_DISTINCT("id");
		} else {
			sql.SELECT("id");
		}
		sql.SELECT("picurl");
		sql.SELECT("url");
		sql.SELECT("status");
		sql.SELECT("seq");
		sql.SELECT("starttime");
		sql.SELECT("endtime");
		sql.SELECT("createtime");
		sql.SELECT("modifydate");
		sql.SELECT("description");
		sql.FROM("sys_notification");
		applyWhere(sql, example, false);
		if (example != null && example.getOrderByClause() != null) {
			sql.ORDER_BY(example.getOrderByClause());
		}
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String updateByExampleSelective(Map<String, Object> parameter) {
		SysNotification record = (SysNotification) parameter.get("record");
		SysNotificationExample example = (SysNotificationExample) parameter.get("example");
		SQL sql = new SQL();
		sql.UPDATE("sys_notification");
		if (record.getId() != null) {
			sql.SET("id = #{record.id,jdbcType=BIGINT}");
		}
		if (record.getPicurl() != null) {
			sql.SET("picurl = #{record.picurl,jdbcType=VARCHAR}");
		}
		if (record.getUrl() != null) {
			sql.SET("url = #{record.url,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			sql.SET("status = #{record.status,jdbcType=VARCHAR}");
		}
		if (record.getSeq() != null) {
			sql.SET("seq = #{record.seq,jdbcType=BIGINT}");
		}
		if (record.getStarttime() != null) {
			sql.SET("starttime = #{record.starttime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndtime() != null) {
			sql.SET("endtime = #{record.endtime,jdbcType=TIMESTAMP}");
		}
		if (record.getCreatetime() != null) {
			sql.SET("createtime = #{record.createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.SET("modifydate = #{record.modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getDescription() != null) {
			sql.SET("description = #{record.description,jdbcType=VARCHAR}");
		}
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String updateByExample(Map<String, Object> parameter) {
		SQL sql = new SQL();
		sql.UPDATE("sys_notification");
		sql.SET("id = #{record.id,jdbcType=BIGINT}");
		sql.SET("picurl = #{record.picurl,jdbcType=VARCHAR}");
		sql.SET("url = #{record.url,jdbcType=VARCHAR}");
		sql.SET("status = #{record.status,jdbcType=VARCHAR}");
		sql.SET("seq = #{record.seq,jdbcType=BIGINT}");
		sql.SET("starttime = #{record.starttime,jdbcType=TIMESTAMP}");
		sql.SET("endtime = #{record.endtime,jdbcType=TIMESTAMP}");
		sql.SET("createtime = #{record.createtime,jdbcType=TIMESTAMP}");
		sql.SET("modifydate = #{record.modifydate,jdbcType=TIMESTAMP}");
		sql.SET("description = #{record.description,jdbcType=VARCHAR}");
		SysNotificationExample example = (SysNotificationExample) parameter.get("example");
		applyWhere(sql, example, true);
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:18:59 CST 2018
	 */
	public String updateByPrimaryKeySelective(SysNotification record) {
		SQL sql = new SQL();
		sql.UPDATE("sys_notification");
		if (record.getPicurl() != null) {
			sql.SET("picurl = #{picurl,jdbcType=VARCHAR}");
		}
		if (record.getUrl() != null) {
			sql.SET("url = #{url,jdbcType=VARCHAR}");
		}
		if (record.getStatus() != null) {
			sql.SET("status = #{status,jdbcType=VARCHAR}");
		}
		if (record.getSeq() != null) {
			sql.SET("seq = #{seq,jdbcType=BIGINT}");
		}
		if (record.getStarttime() != null) {
			sql.SET("starttime = #{starttime,jdbcType=TIMESTAMP}");
		}
		if (record.getEndtime() != null) {
			sql.SET("endtime = #{endtime,jdbcType=TIMESTAMP}");
		}
		if (record.getCreatetime() != null) {
			sql.SET("createtime = #{createtime,jdbcType=TIMESTAMP}");
		}
		if (record.getModifydate() != null) {
			sql.SET("modifydate = #{modifydate,jdbcType=TIMESTAMP}");
		}
		if (record.getDescription() != null) {
			sql.SET("description = #{description,jdbcType=VARCHAR}");
		}
		sql.WHERE("id = #{id,jdbcType=BIGINT}");
		return sql.toString();
	}

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_notification
	 * @mbg.generated  Fri Oct 19 14:19:00 CST 2018
	 */
	protected void applyWhere(SQL sql, SysNotificationExample example, boolean includeExamplePhrase) {
		if (example == null) {
			return;
		}
		String parmPhrase1;
		String parmPhrase1_th;
		String parmPhrase2;
		String parmPhrase2_th;
		String parmPhrase3;
		String parmPhrase3_th;
		if (includeExamplePhrase) {
			parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		} else {
			parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
			parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
			parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
			parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
			parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
			parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
		}
		StringBuilder sb = new StringBuilder();
		List<Criteria> oredCriteria = example.getOredCriteria();
		boolean firstCriteria = true;
		for (int i = 0; i < oredCriteria.size(); i++) {
			Criteria criteria = oredCriteria.get(i);
			if (criteria.isValid()) {
				if (firstCriteria) {
					firstCriteria = false;
				} else {
					sb.append(" or ");
				}
				sb.append('(');
				List<Criterion> criterions = criteria.getAllCriteria();
				boolean firstCriterion = true;
				for (int j = 0; j < criterions.size(); j++) {
					Criterion criterion = criterions.get(j);
					if (firstCriterion) {
						firstCriterion = false;
					} else {
						sb.append(" and ");
					}
					if (criterion.isNoValue()) {
						sb.append(criterion.getCondition());
					} else if (criterion.isSingleValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
						} else {
							sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler()));
						}
					} else if (criterion.isBetweenValue()) {
						if (criterion.getTypeHandler() == null) {
							sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
						} else {
							sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j,
									criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
						}
					} else if (criterion.isListValue()) {
						sb.append(criterion.getCondition());
						sb.append(" (");
						List<?> listItems = (List<?>) criterion.getValue();
						boolean comma = false;
						for (int k = 0; k < listItems.size(); k++) {
							if (comma) {
								sb.append(", ");
							} else {
								comma = true;
							}
							if (criterion.getTypeHandler() == null) {
								sb.append(String.format(parmPhrase3, i, j, k));
							} else {
								sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
							}
						}
						sb.append(')');
					}
				}
				sb.append(')');
			}
		}
		if (sb.length() > 0) {
			sql.WHERE(sb.toString());
		}
	}
}