package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.ActivityInfo;
import it.etoken.base.model.eosblock.entity.ActivityInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface ActivityInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@SelectProvider(type = ActivityInfoSqlProvider.class, method = "countByExample")
	long countByExample(ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@DeleteProvider(type = ActivityInfoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@Delete({ "delete from activity_info", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@Insert({ "insert into activity_info (id, name, ", "status, start_date, ", "end_date, description)",
			"values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
			"#{status,jdbcType=VARCHAR}, #{startDate,jdbcType=TIMESTAMP}, ",
			"#{endDate,jdbcType=TIMESTAMP}, #{description,jdbcType=LONGVARCHAR})" })
	int insert(ActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@InsertProvider(type = ActivityInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(ActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@SelectProvider(type = ActivityInfoSqlProvider.class, method = "selectByExampleWithBLOBs")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "start_date", property = "startDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_date", property = "endDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "description", property = "description", jdbcType = JdbcType.LONGVARCHAR) })
	List<ActivityInfo> selectByExampleWithBLOBs(ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@SelectProvider(type = ActivityInfoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "start_date", property = "startDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_date", property = "endDate", jdbcType = JdbcType.TIMESTAMP) })
	List<ActivityInfo> selectByExample(ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@Select({ "select", "id, name, status, start_date, end_date, description", "from activity_info",
			"where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "status", property = "status", jdbcType = JdbcType.VARCHAR),
			@Result(column = "start_date", property = "startDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "end_date", property = "endDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "description", property = "description", jdbcType = JdbcType.LONGVARCHAR) })
	ActivityInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@UpdateProvider(type = ActivityInfoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") ActivityInfo record, @Param("example") ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@UpdateProvider(type = ActivityInfoSqlProvider.class, method = "updateByExampleWithBLOBs")
	int updateByExampleWithBLOBs(@Param("record") ActivityInfo record, @Param("example") ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@UpdateProvider(type = ActivityInfoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") ActivityInfo record, @Param("example") ActivityInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@UpdateProvider(type = ActivityInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(ActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@Update({ "update activity_info", "set name = #{name,jdbcType=VARCHAR},", "status = #{status,jdbcType=VARCHAR},",
			"start_date = #{startDate,jdbcType=TIMESTAMP},", "end_date = #{endDate,jdbcType=TIMESTAMP},",
			"description = #{description,jdbcType=LONGVARCHAR}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKeyWithBLOBs(ActivityInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table activity_info
	 * @mbg.generated  Fri Sep 21 16:17:12 CST 2018
	 */
	@Update({ "update activity_info", "set name = #{name,jdbcType=VARCHAR},", "status = #{status,jdbcType=VARCHAR},",
			"start_date = #{startDate,jdbcType=TIMESTAMP},", "end_date = #{endDate,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(ActivityInfo record);
}