package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.DappInfo;
import it.etoken.base.model.eosblock.entity.DappInfoExample;

import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface DappInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@SelectProvider(type = DappInfoSqlProvider.class, method = "countByExample")
	long countByExample(DappInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@DeleteProvider(type = DappInfoSqlProvider.class, method = "deleteByExample")
	int deleteByExample(DappInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@Delete({ "delete from dapp_info", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@Insert({ "insert into dapp_info (id, category_id, ", "name, icon, description, ", "url, is_recommend, ",
			"seq, create_date, ", "update_date)", "values (#{id,jdbcType=BIGINT}, #{categoryId,jdbcType=BIGINT}, ",
			"#{name,jdbcType=VARCHAR}, #{icon,jdbcType=VARCHAR}, #{description,jdbcType=VARCHAR}, ",
			"#{url,jdbcType=VARCHAR}, #{isRecommend,jdbcType=VARCHAR}, ",
			"#{seq,jdbcType=BIGINT}, #{createDate,jdbcType=TIMESTAMP}, ", "#{updateDate,jdbcType=TIMESTAMP})" })
	int insert(DappInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@InsertProvider(type = DappInfoSqlProvider.class, method = "insertSelective")
	int insertSelective(DappInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@SelectProvider(type = DappInfoSqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "category_id", property = "categoryId", jdbcType = JdbcType.BIGINT),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "icon", property = "icon", jdbcType = JdbcType.VARCHAR),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_recommend", property = "isRecommend", jdbcType = JdbcType.VARCHAR),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP) })
	List<DappInfo> selectByExample(DappInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@Select({ "select", "id, category_id, name, icon, description, url, is_recommend, seq, create_date, ",
			"update_date", "from dapp_info", "where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "category_id", property = "categoryId", jdbcType = JdbcType.BIGINT),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "icon", property = "icon", jdbcType = JdbcType.VARCHAR),
			@Result(column = "description", property = "description", jdbcType = JdbcType.VARCHAR),
			@Result(column = "url", property = "url", jdbcType = JdbcType.VARCHAR),
			@Result(column = "is_recommend", property = "isRecommend", jdbcType = JdbcType.VARCHAR),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP) })
	DappInfo selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@UpdateProvider(type = DappInfoSqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") DappInfo record, @Param("example") DappInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@UpdateProvider(type = DappInfoSqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") DappInfo record, @Param("example") DappInfoExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@UpdateProvider(type = DappInfoSqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(DappInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_info
	 * @mbg.generated  Sat Sep 08 14:00:13 CST 2018
	 */
	@Update({ "update dapp_info", "set category_id = #{categoryId,jdbcType=BIGINT},",
			"name = #{name,jdbcType=VARCHAR},", "icon = #{icon,jdbcType=VARCHAR},",
			"description = #{description,jdbcType=VARCHAR},", "url = #{url,jdbcType=VARCHAR},",
			"is_recommend = #{isRecommend,jdbcType=VARCHAR},", "seq = #{seq,jdbcType=BIGINT},",
			"create_date = #{createDate,jdbcType=TIMESTAMP},", "update_date = #{updateDate,jdbcType=TIMESTAMP}",
			"where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(DappInfo record);
}