package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.DappCategory;
import it.etoken.base.model.eosblock.entity.DappCategoryExample;
import it.etoken.component.eosblock.dao.provider.DappCategorySqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;

@Mapper
public interface DappCategoryMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@SelectProvider(type = DappCategorySqlProvider.class, method = "countByExample")
	long countByExample(DappCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@DeleteProvider(type = DappCategorySqlProvider.class, method = "deleteByExample")
	int deleteByExample(DappCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@Delete({ "delete from dapp_category", "where id = #{id,jdbcType=BIGINT}" })
	int deleteByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@Insert({ "insert into dapp_category (id, name, ", "create_date, update_date, ", "seq)",
			"values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
			"#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP}, ", "#{seq,jdbcType=BIGINT})" })
	int insert(DappCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@InsertProvider(type = DappCategorySqlProvider.class, method = "insertSelective")
	int insertSelective(DappCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@SelectProvider(type = DappCategorySqlProvider.class, method = "selectByExample")
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT) })
	List<DappCategory> selectByExample(DappCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@Select({ "select", "id, name, create_date, update_date, seq", "from dapp_category",
			"where id = #{id,jdbcType=BIGINT}" })
	@Results({ @Result(column = "id", property = "id", jdbcType = JdbcType.BIGINT, id = true),
			@Result(column = "name", property = "name", jdbcType = JdbcType.VARCHAR),
			@Result(column = "create_date", property = "createDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "update_date", property = "updateDate", jdbcType = JdbcType.TIMESTAMP),
			@Result(column = "seq", property = "seq", jdbcType = JdbcType.BIGINT) })
	DappCategory selectByPrimaryKey(Long id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@UpdateProvider(type = DappCategorySqlProvider.class, method = "updateByExampleSelective")
	int updateByExampleSelective(@Param("record") DappCategory record, @Param("example") DappCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@UpdateProvider(type = DappCategorySqlProvider.class, method = "updateByExample")
	int updateByExample(@Param("record") DappCategory record, @Param("example") DappCategoryExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@UpdateProvider(type = DappCategorySqlProvider.class, method = "updateByPrimaryKeySelective")
	int updateByPrimaryKeySelective(DappCategory record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dapp_category
	 * @mbg.generated  Mon Oct 08 15:19:46 CST 2018
	 */
	@Update({ "update dapp_category", "set name = #{name,jdbcType=VARCHAR},",
			"create_date = #{createDate,jdbcType=TIMESTAMP},", "update_date = #{updateDate,jdbcType=TIMESTAMP},",
			"seq = #{seq,jdbcType=BIGINT}", "where id = #{id,jdbcType=BIGINT}" })
	int updateByPrimaryKey(DappCategory record);
}