package it.etoken.component.eosblock.dao.mapper;

import it.etoken.base.model.eosblock.entity.DappCategory;
import it.etoken.base.model.eosblock.entity.DappCategoryExample;
import it.etoken.component.eosblock.dao.provider.DappCategorySqlProvider;

import java.util.List;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

@Mapper
public interface DappCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @SelectProvider(type=DappCategorySqlProvider.class, method="countByExample")
    long countByExample(DappCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @DeleteProvider(type=DappCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(DappCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @Insert({
        "insert into dapp_category (id, name, ",
        "create_date, update_date)",
        "values (#{id,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=TIMESTAMP}, #{updateDate,jdbcType=TIMESTAMP})"
    })
    int insert(DappCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @InsertProvider(type=DappCategorySqlProvider.class, method="insertSelective")
    int insertSelective(DappCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @SelectProvider(type=DappCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.BIGINT),
        @Result(column="name", property="name", jdbcType=JdbcType.VARCHAR),
        @Result(column="create_date", property="createDate", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="update_date", property="updateDate", jdbcType=JdbcType.TIMESTAMP)
    })
    List<DappCategory> selectByExample(DappCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @UpdateProvider(type=DappCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") DappCategory record, @Param("example") DappCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dapp_category
     *
     * @mbg.generated Tue Sep 04 14:48:21 CST 2018
     */
    @UpdateProvider(type=DappCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") DappCategory record, @Param("example") DappCategoryExample example);
}