package it.etoken.base.model.news.entity;

import java.io.Serializable;
import java.util.Date;


public class SysNotification  implements Serializable{
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.id
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Long id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.picurl
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private String picurl;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.url
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private String url;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.status
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Long status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.seq
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Long seq;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.starttime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Date starttime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.endtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Date endtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.createtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Date createtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_notification.modifydate
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	private Date modifydate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.id
	 * @return  the value of sys_notification.id
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.id
	 * @param id  the value for sys_notification.id
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.picurl
	 * @return  the value of sys_notification.picurl
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public String getPicurl() {
		return picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.picurl
	 * @param picurl  the value for sys_notification.picurl
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setPicurl(String picurl) {
		this.picurl = picurl;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.url
	 * @return  the value of sys_notification.url
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public String getUrl() {
		return url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.url
	 * @param url  the value for sys_notification.url
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setUrl(String url) {
		this.url = url;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.status
	 * @return  the value of sys_notification.status
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Long getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.status
	 * @param status  the value for sys_notification.status
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setStatus(Long status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.seq
	 * @return  the value of sys_notification.seq
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Long getSeq() {
		return seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.seq
	 * @param seq  the value for sys_notification.seq
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setSeq(Long seq) {
		this.seq = seq;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.starttime
	 * @return  the value of sys_notification.starttime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Date getStarttime() {
		return starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.starttime
	 * @param starttime  the value for sys_notification.starttime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setStarttime(Date starttime) {
		this.starttime = starttime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.endtime
	 * @return  the value of sys_notification.endtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Date getEndtime() {
		return endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.endtime
	 * @param endtime  the value for sys_notification.endtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setEndtime(Date endtime) {
		this.endtime = endtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.createtime
	 * @return  the value of sys_notification.createtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Date getCreatetime() {
		return createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.createtime
	 * @param createtime  the value for sys_notification.createtime
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setCreatetime(Date createtime) {
		this.createtime = createtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_notification.modifydate
	 * @return  the value of sys_notification.modifydate
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public Date getModifydate() {
		return modifydate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_notification.modifydate
	 * @param modifydate  the value for sys_notification.modifydate
	 * @mbg.generated  Wed Oct 10 15:13:46 CST 2018
	 */
	public void setModifydate(Date modifydate) {
		this.modifydate = modifydate;
	}

	/**
	 * 
	 */
	private static final long serialVersionUID = -8190124304964955019L;
}