ALTER TABLE coins ADD issue_date DATETIME DEFAULT NULL COMMENT '发行时间';
ALTER TABLE coins ADD crowdfunding_price VARCHAR(50) DEFAULT NULL COMMENT '众筹价格';
ALTER TABLE coins ADD white_paper_url VARCHAR(50) DEFAULT NULL COMMENT '白皮书URL';
ALTER TABLE coins ADD block_query_url VARCHAR(50) DEFAULT NULL COMMENT '区块查询URL';